# ----
# Site

title: Legal Luminary Platform
url: "https://legalluminary.com/"
baseurl:  "http://luminarylegal.com/"
google_analytics_key: MY_GOOGLE_ANALYTICS_KEY
google_maps_javascript_api_key: MY_GOOGLE_MAPS_API_KEY_HERE
disqus_shortname: llp
logo: /siteicon.png

# Build

timezone: US/Pacific

paginate: 10
paginate_path: "/blog/:num/"

collections:
  - "staff_members"
  - "attorneys"
  - "paralegals"
  - "case_management"
  - "complaints"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /uploads/building.jpg
      image: /uploads/building.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the blog list.
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image:
          width: 440
          height: 440

permalink: pretty

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# legalluminary

_select_data:
  call_to_actions:
    - Contact
    - Blog
    - Map
    - File

  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS

_comments:
  large_header: Toggles the size of the top banner.
  show_in_navigation: Toggles a link in the top banner.
  author_staff_member: The staff member writing this post.
  call_to_action: Type of request shown at the bottom of this page.
  background_image_path: Image shown in the top banner, blank for the default.
  testimonials: Update, add or remove testimonials.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  phone_extension: The digits after dialing the company phone.
  credentials: Shown as subtext on staff member summaries.
  contact_email_address: Address for the contact form to send to.
  new_window: Whether the link opens a new browser tab/window.
